package pontocristao.visao;

import java.awt.Desktop;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Properties;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.export.JRPdfExporter;
import pontocristao.controle.ControleSistema;
import pontocristao.util.Utilidades;

/**
 *
 * @author Marcondes
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();

        this.setLocationRelativeTo(this);
        //this.setExtendedState(MAXIMIZED_BOTH);
        //PopularBancoTeste.Popular();

        LblFuncionarioLogado.setText(ControleSistema.FuncionarioLogado.getNome());
        Timer timer = new Timer();

        timer.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {

                Date date = new Date();
                String dataFormatada = new SimpleDateFormat("dd/MM/yyyy HH:mm").format(date);
                lData.setText(dataFormatada);
            }
        }, 0, 60 * 1000);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnSair = new javax.swing.JButton();
        LblFuncionarioLogado = new javax.swing.JLabel();
        lData = new javax.swing.JLabel();
        lImagem = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");

        BtnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocristao/icones/BtnSairPrincipal.png"))); // NOI18N
        BtnSair.setText("Sair");
        BtnSair.setPreferredSize(new java.awt.Dimension(139, 65));
        BtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSairActionPerformed(evt);
            }
        });

        LblFuncionarioLogado.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        LblFuncionarioLogado.setText("Usuário Logado no Sistema");

        lData.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lData.setText("Data e Hora");

        lImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocristao/icones/ImagemPrincipal.png"))); // NOI18N

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocristao/icones/Opcoes.png"))); // NOI18N
        jMenu1.setText("Opções");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocristao/icones/Funcionario.png"))); // NOI18N
        jMenuItem2.setText("Funcionário");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocristao/icones/CadastrarCliente.png"))); // NOI18N
        jMenuItem1.setText("Cliente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocristao/icones/Fornecedor.png"))); // NOI18N
        jMenuItem4.setText("Fornecedor");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocristao/icones/Filme.png"))); // NOI18N
        jMenu3.setText("Filme");

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocristao/icones/CadastrarFilme.png"))); // NOI18N
        jMenuItem7.setText("Cadastrar Filme");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocristao/icones/CadastrarTipoFilme.png"))); // NOI18N
        jMenuItem8.setText("Cadastrar Tipo de Filme");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenu1.add(jMenu3);

        jMenuItem20.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocristao/icones/Locacao.png"))); // NOI18N
        jMenuItem20.setText("Locação");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem20);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocristao/icones/TabelaDePreco.png"))); // NOI18N
        jMenuItem3.setText("Tabela de Preço");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocristao/icones/Produto.png"))); // NOI18N
        jMenu4.setText("Produto");

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocristao/icones/CadastrarProduto.png"))); // NOI18N
        jMenuItem9.setText("Cadastrar Produto");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9);

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocristao/icones/CadastrarTipoProduto.png"))); // NOI18N
        jMenuItem10.setText("Cadastrar Tipo de Produto");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem10);

        jMenu1.add(jMenu4);

        jMenuItem21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocristao/icones/Venda.png"))); // NOI18N
        jMenuItem21.setText("Venda");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem21);

        jMenuItem22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocristao/icones/Caixa.png"))); // NOI18N
        jMenuItem22.setText("Caixa");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem22);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocristao/icones/Contas.png"))); // NOI18N
        jMenu7.setText("Conta a Pagar");

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocristao/icones/BtnContaPagar.png"))); // NOI18N
        jMenuItem6.setText("Cadastrar Conta a Pagar");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem6);

        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocristao/icones/BtnTipoContaPagar.png"))); // NOI18N
        jMenuItem15.setText("Cadastrar Tipo de Conta a Pagar");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem15);

        jMenu1.add(jMenu7);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocristao/icones/Relatorio.png"))); // NOI18N
        jMenu2.setText("Relatórios");

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocristao/icones/RelatorioCliente.png"))); // NOI18N
        jMenuItem5.setText("Cliente");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocristao/icones/RelatorioFuncionario.png"))); // NOI18N
        jMenuItem11.setText("Funcionário");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem11);

        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocristao/icones/RelatorioFornecedor.png"))); // NOI18N
        jMenuItem12.setText("Fornecedor");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem12);

        jMenuItem25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocristao/icones/RelatorioConta.png"))); // NOI18N
        jMenuItem25.setText("Conta");
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem25);

        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocristao/icones/RelatorioFilme.png"))); // NOI18N
        jMenuItem14.setText("Filme");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem14);

        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocristao/icones/RelatorioProduto.png"))); // NOI18N
        jMenuItem13.setText("Produto");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem13);

        jMenuItem24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocristao/icones/RelatorioLocacao.png"))); // NOI18N
        jMenuItem24.setText("Locação");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem24);

        jMenuItem23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocristao/icones/RelatorioVenda.png"))); // NOI18N
        jMenuItem23.setText("Venda");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem23);

        jMenuItem26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocristao/icones/RelatorioCaixa.png"))); // NOI18N
        jMenuItem26.setText("Caixa");
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem26);

        jMenuBar1.add(jMenu2);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocristao/icones/Ajuda.png"))); // NOI18N
        jMenu5.setText("Ajuda");

        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocristao/icones/Contato.png"))); // NOI18N
        jMenuItem17.setText("Contato");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem17);

        jMenuBar1.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocristao/icones/BtnSairPrincipal.png"))); // NOI18N
        jMenu6.setText("Sair");

        jMenuItem18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocristao/icones/SairSistema.png"))); // NOI18N
        jMenuItem18.setText("Sair do Sistema");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem18);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lData)
                            .addComponent(LblFuncionarioLogado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LblFuncionarioLogado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lData))
                    .addComponent(BtnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FrmFuncionario frmFuncionario = FrmFuncionario.Mostrar(this);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FrmCliente frmCliente = FrmCliente.Mostrar(this);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        FrmFornecedor frmFornecedor = FrmFornecedor.Mostrar(this);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        FrmFilme frmFilme = FrmFilme.Mostrar(this);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        FrmTipoFilme frm = FrmTipoFilme.Mostrar(this);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        FrmProduto frmProduto = FrmProduto.Mostrar(this);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        FrmTipoProduto frm = FrmTipoProduto.Mostrar(this);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void BtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSairActionPerformed
        Object[] botoes = {"Sim", "Não"};
        int resposta = JOptionPane.showOptionDialog(null,
                "Deseja sair do sistema?",
                "Confirmação",
                JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null,
                botoes, botoes[0]);
        if (resposta == 0) {
            this.dispose();
            System.exit(0);
        }
    }//GEN-LAST:event_BtnSairActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        FrmDataRelatorio frm = FrmDataRelatorio.Mostrar(this, "Relatório de Clientes");

        if (frm.Confirmou) {

            String relatorio = ".\\Relatorios\\RelatorioCliente.jasper";
            String arquivo = ".\\Relatorios.\\RelatorioCliente.pdf";

            try {
                Properties connectionProps = new Properties();
                connectionProps.put("user", "root");
                connectionProps.put("password", "root");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pontocristao", connectionProps);

                HashMap parametros = new HashMap();
                
                DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
                parametros.put("DATA_INICIO", df.format(frm.DataInicio));
                parametros.put("DATA_FIM", df.format(frm.DataLimite));

                JasperPrint jp = JasperFillManager.fillReport(relatorio, parametros, conn);

                JRExporter exporter = new JRPdfExporter();
                exporter.setParameter(JRExporterParameter.OUTPUT_FILE_NAME, arquivo);
                exporter.setParameter(JRExporterParameter.JASPER_PRINT, jp);

                exporter.exportReport();

                File myFile = new File(arquivo);
                Desktop.getDesktop().open(myFile);

            } catch (Exception ex) {
                Utilidades.MostrarMensagemErro(ex);
            }

        }

    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        FrmLocacao frmLocacao = FrmLocacao.Mostrar(this);
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        FrmTabelaPrecoLocacao frmTabelaPrecoLocacao = FrmTabelaPrecoLocacao.Mostrar(this);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
//        FrmDataRelatorio frm = FrmDataRelatorio.Mostrar(this, "Relatório de Fornecedores");
//
//        if (frm.Confirmou) {

            String relatorio = ".\\Relatorios\\RelatorioFornecedor.jasper";
            String arquivo = ".\\Relatorios.\\RelatorioFornecedor.pdf";

            try {
                Properties connectionProps = new Properties();
                connectionProps.put("user", "root");
                connectionProps.put("password", "root");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pontocristao", connectionProps);

                HashMap parametros = new HashMap();

//                DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
//                parametros.put("DATA_INICIO", df.format(frm.DataInicio));
//                parametros.put("DATA_FIM", df.format(frm.DataLimite));

                JasperPrint jp = JasperFillManager.fillReport(relatorio, parametros, conn);

                JRExporter exporter = new JRPdfExporter();
                exporter.setParameter(JRExporterParameter.OUTPUT_FILE_NAME, arquivo);
                exporter.setParameter(JRExporterParameter.JASPER_PRINT, jp);

                exporter.exportReport();

                File myFile = new File(arquivo);
                Desktop.getDesktop().open(myFile);

            } catch (Exception ex) {
                Utilidades.MostrarMensagemErro(ex);
            }
//        }
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        FrmDataRelatorio frm = FrmDataRelatorio.Mostrar(this, "Relatório de Filmes");

        if (frm.Confirmou) {

            String relatorio = ".\\Relatorios\\RelatorioFilme.jasper";
            String arquivo = ".\\Relatorios.\\RelatorioFilme.pdf";

            try {
                Properties connectionProps = new Properties();
                connectionProps.put("user", "root");
                connectionProps.put("password", "root");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pontocristao", connectionProps);

                HashMap parametros = new HashMap();

                DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
                parametros.put("DATA_INICIO", df.format(frm.DataInicio));
                parametros.put("DATA_FIM", df.format(frm.DataLimite));

                JasperPrint jp = JasperFillManager.fillReport(relatorio, parametros, conn);

                JRExporter exporter = new JRPdfExporter();
                exporter.setParameter(JRExporterParameter.OUTPUT_FILE_NAME, arquivo);
                exporter.setParameter(JRExporterParameter.JASPER_PRINT, jp);

                exporter.exportReport();

                File myFile = new File(arquivo);
                Desktop.getDesktop().open(myFile);

            } catch (Exception ex) {
                Utilidades.MostrarMensagemErro(ex);
            }
        }
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        FrmCaixa frmCaixa = FrmCaixa.Mostrar(this);
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        FrmContato frmContato = FrmContato.Mostrar(this);
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        FrmDataRelatorio frm = FrmDataRelatorio.Mostrar(this, "Relatório de Funcionários");

        if (frm.Confirmou) {

            String relatorio = ".\\Relatorios\\RelatorioFuncionario.jasper";
            String arquivo = ".\\Relatorios.\\RelatorioFuncionario.pdf";

            try {
                Properties connectionProps = new Properties();
                connectionProps.put("user", "root");
                connectionProps.put("password", "root");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pontocristao", connectionProps);

                HashMap parametros = new HashMap();

                DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
                parametros.put("DATA_INICIO", df.format(frm.DataInicio));
                parametros.put("DATA_FIM", df.format(frm.DataLimite));

                JasperPrint jp = JasperFillManager.fillReport(relatorio, parametros, conn);

                JRExporter exporter = new JRPdfExporter();
                exporter.setParameter(JRExporterParameter.OUTPUT_FILE_NAME, arquivo);
                exporter.setParameter(JRExporterParameter.JASPER_PRINT, jp);

                exporter.exportReport();

                File myFile = new File(arquivo);
                Desktop.getDesktop().open(myFile);

            } catch (Exception ex) {
                Utilidades.MostrarMensagemErro(ex);
            }
        }
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        Object[] botoes = {"Sim", "Não"};
        int resposta = JOptionPane.showOptionDialog(null,
                "Deseja sair do sistema?",
                "Confirmação",
                JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null,
                botoes, botoes[0]);
        if (resposta == 0) {
            this.dispose();
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem25ActionPerformed
        FrmDataRelatorio frm = FrmDataRelatorio.Mostrar(this, "Relatório de Contas a Pagar");

        if (frm.Confirmou) {

            String relatorio = ".\\Relatorios\\RelatorioContaPagar.jasper";
            String arquivo = ".\\Relatorios.\\RelatorioContaPagar.pdf";

            try {
                Properties connectionProps = new Properties();
                connectionProps.put("user", "root");
                connectionProps.put("password", "root");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pontocristao", connectionProps);

                HashMap parametros = new HashMap();

                DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
                parametros.put("DATA_INICIO", df.format(frm.DataInicio));
                parametros.put("DATA_FIM", df.format(frm.DataLimite));

                JasperPrint jp = JasperFillManager.fillReport(relatorio, parametros, conn);

                JRExporter exporter = new JRPdfExporter();
                exporter.setParameter(JRExporterParameter.OUTPUT_FILE_NAME, arquivo);
                exporter.setParameter(JRExporterParameter.JASPER_PRINT, jp);

                exporter.exportReport();

                File myFile = new File(arquivo);
                Desktop.getDesktop().open(myFile);

            } catch (Exception ex) {
                Utilidades.MostrarMensagemErro(ex);
            }
        }
    }//GEN-LAST:event_jMenuItem25ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        FrmDataRelatorio frm = FrmDataRelatorio.Mostrar(this, "Relatório de Produtos");

        if (frm.Confirmou) {

            String relatorio = ".\\Relatorios\\RelatorioProduto.jasper";
            String arquivo = ".\\Relatorios.\\RelatorioProduto.pdf";

            try {
                Properties connectionProps = new Properties();
                connectionProps.put("user", "root");
                connectionProps.put("password", "root");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pontocristao", connectionProps);

                HashMap parametros = new HashMap();

                DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
                parametros.put("DATA_INICIO", df.format(frm.DataInicio));
                parametros.put("DATA_FIM", df.format(frm.DataLimite));

                JasperPrint jp = JasperFillManager.fillReport(relatorio, parametros, conn);

                JRExporter exporter = new JRPdfExporter();
                exporter.setParameter(JRExporterParameter.OUTPUT_FILE_NAME, arquivo);
                exporter.setParameter(JRExporterParameter.JASPER_PRINT, jp);

                exporter.exportReport();

                File myFile = new File(arquivo);
                Desktop.getDesktop().open(myFile);

            } catch (Exception ex) {
                Utilidades.MostrarMensagemErro(ex);
            }
        }
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        FrmDataRelatorio frm = FrmDataRelatorio.Mostrar(this, "Relatório de Locação");

        if (frm.Confirmou) {

            String relatorio = ".\\Relatorios\\RelatorioLocacao.jasper";
            String arquivo = ".\\Relatorios.\\RelatorioLocacao.pdf";

            try {
                Properties connectionProps = new Properties();
                connectionProps.put("user", "root");
                connectionProps.put("password", "root");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pontocristao", connectionProps);

                HashMap parametros = new HashMap();

                DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
                parametros.put("DATA_INICIO", df.format(frm.DataInicio));
                parametros.put("DATA_FIM", df.format(frm.DataLimite));

                JasperPrint jp = JasperFillManager.fillReport(relatorio, parametros, conn);

                JRExporter exporter = new JRPdfExporter();
                exporter.setParameter(JRExporterParameter.OUTPUT_FILE_NAME, arquivo);
                exporter.setParameter(JRExporterParameter.JASPER_PRINT, jp);

                exporter.exportReport();

                File myFile = new File(arquivo);
                Desktop.getDesktop().open(myFile);

            } catch (Exception ex) {
                Utilidades.MostrarMensagemErro(ex);
            }
        }
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        FrmDataRelatorio frm = FrmDataRelatorio.Mostrar(this, "Relatório de Vendas");

        if (frm.Confirmou) {

            String relatorio = ".\\Relatorios\\RelatorioVenda.jasper";
            String arquivo = ".\\Relatorios.\\RelatorioVenda.pdf";

            try {
                Properties connectionProps = new Properties();
                connectionProps.put("user", "root");
                connectionProps.put("password", "root");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pontocristao", connectionProps);

                HashMap parametros = new HashMap();

                DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
                parametros.put("DATA_INICIO", df.format(frm.DataInicio));
                parametros.put("DATA_FIM", df.format(frm.DataLimite));

                JasperPrint jp = JasperFillManager.fillReport(relatorio, parametros, conn);

                JRExporter exporter = new JRPdfExporter();
                exporter.setParameter(JRExporterParameter.OUTPUT_FILE_NAME, arquivo);
                exporter.setParameter(JRExporterParameter.JASPER_PRINT, jp);

                exporter.exportReport();

                File myFile = new File(arquivo);
                Desktop.getDesktop().open(myFile);

            } catch (Exception ex) {
                Utilidades.MostrarMensagemErro(ex);
            }
        }
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed
        FrmDataRelatorio frm = FrmDataRelatorio.Mostrar(this, "Relatório de Caixa");

        if (frm.Confirmou) {

            String relatorio = ".\\Relatorios\\RelatorioCaixa.jasper";
            String arquivo = ".\\Relatorios.\\RelatorioCaixa.pdf";

            try {
                Properties connectionProps = new Properties();
                connectionProps.put("user", "root");
                connectionProps.put("password", "root");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pontocristao", connectionProps);

                HashMap parametros = new HashMap();

                DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
                parametros.put("DATA_INICIO", df.format(frm.DataInicio));
                parametros.put("DATA_FIM", df.format(frm.DataLimite));

                JasperPrint jp = JasperFillManager.fillReport(relatorio, parametros, conn);

                JRExporter exporter = new JRPdfExporter();
                exporter.setParameter(JRExporterParameter.OUTPUT_FILE_NAME, arquivo);
                exporter.setParameter(JRExporterParameter.JASPER_PRINT, jp);

                exporter.exportReport();

                File myFile = new File(arquivo);
                Desktop.getDesktop().open(myFile);

            } catch (Exception ex) {
                Utilidades.MostrarMensagemErro(ex);
            }
        }
    }//GEN-LAST:event_jMenuItem26ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        FrmVenda frmVenda = FrmVenda.Mostrar(this);
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        FrmContaPagar frmContaPagar = FrmContaPagar.Mostrar(this);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        FrmTipoContaPagar frmTipoContaPagar = FrmTipoContaPagar.Mostrar(this);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSair;
    private javax.swing.JLabel LblFuncionarioLogado;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JLabel lData;
    private javax.swing.JLabel lImagem;
    // End of variables declaration//GEN-END:variables

}
