package pontocristao.visao;

import java.awt.Frame;
import java.util.Date;
import javax.swing.JOptionPane;
import org.hibernate.Transaction;
import pontocristao.controle.ControleCaixa;
import pontocristao.controle.ControleSistema;
import pontocristao.controle.ControleVenda;
import pontocristao.modelo.MovimentacaoCaixaVenda;
import pontocristao.modelo.Venda;
import pontocristao.modelo.PagamentoVenda;
import pontocristao.modelo.TipoPagamento;
import pontocristao.util.Utilidades;

/**
 *
 * @author Marcondes
 */
public class FrmPagamentoVenda extends javax.swing.JDialog {

    private static Frame frame;
    private ControleVenda controle;
    private Boolean modeloAtualizado = false;
    private java.util.List<TipoPagamento> listaTiposPagamento;
    private double valorTotalPagar;

    public Boolean getModeloAtualizado() {
        return modeloAtualizado;
    }

    public Venda getVenda() {
        return controle.getVenda();
    }

    public FrmPagamentoVenda(java.awt.Frame parent, boolean modal, long id) {
        super(parent, modal);
        initComponents();

        this.setLocationRelativeTo(null);

        InicializarControle(id);
    }

    public static FrmPagamentoVenda Mostrar(java.awt.Frame parent, long idLocacao) {
        frame = parent;
        FrmPagamentoVenda frmPagamentoVenda = new FrmPagamentoVenda(parent, true, idLocacao);
        frmPagamentoVenda.setVisible(true);
        return frmPagamentoVenda;
    }

    private void InicializarControle(long id) {
        controle = new ControleVenda();

        listaTiposPagamento = controle.RetornarTiposPagamento();

        for (TipoPagamento tipoPagamento : listaTiposPagamento) {
            jcbTipoPagamento.addItem(tipoPagamento.getDescricao());
        }

        jcbTipoPagamento.setSelectedIndex(0);

        if (id > 0) {
            Exception erro = controle.RecuperarVenda(id);

            if (erro != null) {
                Utilidades.MostrarMensagemErro(erro);
            } else {
                AtualizarCampos();
            }
        } else {
            Utilidades.MostrarMensagemErro(new Exception("O Id da venda deve ser maior que zero."));
            this.dispose();
        }
    }

    private void AtualizarCampos() {
        jcDataPagamento.setDate(new Date());

        AtualizarValor();

        txtDescricao.setText(RetornarDescricaoPagamento());
    }

    private void AtualizarValor() {
        double valor = getVenda().getValorTotal();

        for (PagamentoVenda pagamento : getVenda().getPagamentos()) {
            if (!pagamento.getExcluido()) {
                valor -= pagamento.getValor();
            }
        }

        valorTotalPagar = valor;
        jspValor.setValue(valor);
    }

    private String RetornarDescricaoPagamento() {
        if (jcbTipoPagamento.getSelectedIndex() >= 0) {
            return "Pagamento " + listaTiposPagamento.get(jcbTipoPagamento.getSelectedIndex()).getDescricao();
        } else {
            return "";
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbTipoPagamento = new javax.swing.JComboBox<>();
        jspValor = new javax.swing.JSpinner();
        lDataPagamento = new javax.swing.JLabel();
        jcDataPagamento = new com.toedter.calendar.JDateChooser();
        lValor = new javax.swing.JLabel();
        lDescricao = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        BtnCancelar = new javax.swing.JButton();
        BtnConfirmar = new javax.swing.JButton();
        lTipoPagamento = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jspValor.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));
        jspValor.setEditor(new javax.swing.JSpinner.NumberEditor(jspValor, "R$ ###,###.##"));
        jspValor.setOpaque(false);

        lDataPagamento.setText("Data do Pagamento");

        lValor.setText("Valor");

        lDescricao.setText("Descrição");

        BtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocristao/icones/BtnCancelar.png"))); // NOI18N
        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        BtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pontocristao/icones/BtnConfirmar.png"))); // NOI18N
        BtnConfirmar.setText("Confirmar");
        BtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConfirmarActionPerformed(evt);
            }
        });

        lTipoPagamento.setText("Tipo de Pagamento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbTipoPagamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtDescricao, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jcDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jspValor))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(lDataPagamento)
                                            .addGap(63, 63, 63))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lDescricao)
                                            .addGap(112, 112, 112)))
                                    .addComponent(lValor)
                                    .addGap(124, 124, 124)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnConfirmar)
                                .addGap(18, 18, 18)
                                .addComponent(BtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lTipoPagamento))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lTipoPagamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbTipoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDataPagamento)
                    .addComponent(lValor, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jspValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lDescricao)
                .addGap(1, 1, 1)
                .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jspValor.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 0.1d));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        Object[] botoes = {"Sim", "Não"};
        int resposta = JOptionPane.showOptionDialog(null,
                "Deseja cancelar a venda? ",
                "Confirmação",
                JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null,
                botoes, botoes[0]);
        if (resposta == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void BtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConfirmarActionPerformed
        double valor = (double) jspValor.getValue();
        if (valor > 0 && valor <= valorTotalPagar) {
            try {

                PagamentoVenda pagamento = new PagamentoVenda();
                pagamento.setData(new Date());
                pagamento.setDescricao(txtDescricao.getText());
                pagamento.setVenda(getVenda());
                pagamento.setTipoPagamento(listaTiposPagamento.get(jcbTipoPagamento.getSelectedIndex()));
                pagamento.setValor(valor);

                getVenda().setPago(valor == valorTotalPagar);

                Transaction transacao = controle.getSessao().getTransaction();
                transacao.begin();

                controle.getSessao().saveOrUpdate(pagamento);
                controle.getSessao().saveOrUpdate(getVenda());

                ControleCaixa controleCaixa = new ControleCaixa(controle.getSessao());

                MovimentacaoCaixaVenda movimentacao = new MovimentacaoCaixaVenda();
                movimentacao.setData(new Date());
                movimentacao.setFuncionario(ControleSistema.getFuncionarioLogado(controle.getSessao()));
                movimentacao.setVenda(getVenda());
                movimentacao.setValor(valor);

                controleCaixa.AdicionarMovimentacao(movimentacao);

                transacao.commit();

                modeloAtualizado = true;

                this.dispose();

            } catch (Exception e) {
                Utilidades.MostrarMensagemErro(e);
            }

        } else {
            Utilidades.MostrarMensagemErro(new Exception("O valor está fora do limite aceito e será recalculado."));
            AtualizarValor();
        }
    }//GEN-LAST:event_BtnConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPagamentoVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPagamentoVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPagamentoVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPagamentoVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmPagamentoVenda dialog = new FrmPagamentoVenda(new javax.swing.JFrame(), true, 0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnConfirmar;
    private com.toedter.calendar.JDateChooser jcDataPagamento;
    private javax.swing.JComboBox<String> jcbTipoPagamento;
    private javax.swing.JSpinner jspValor;
    private javax.swing.JLabel lDataPagamento;
    private javax.swing.JLabel lDescricao;
    private javax.swing.JLabel lTipoPagamento;
    private javax.swing.JLabel lValor;
    private javax.swing.JTextField txtDescricao;
    // End of variables declaration//GEN-END:variables
}
